# Generated by Django 2.1 on 2018-10-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20180920_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='external_id',
            field=models.CharField(blank=True, max_length=31, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='external_id',
            field=models.CharField(blank=True, max_length=31, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
