# Generated by Django 2.0.7 on 2018-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20180808_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_terminated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_terminated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
