# Generated by Django 2.1 on 2018-08-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetransaction',
            options={'permissions': (('approve_expensetransaction', 'Can approve expenses'),)},
        ),
    ]
