# Generated by Django 2.1 on 2018-09-21 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_revenuetransaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuetransaction', to='finance.RevenueLedgerAccount'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuetransaction', to='schoolauth.School'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuetransaction', to='finance.StudentAccount'),
        ),
        migrations.AddField(
            model_name='revenueledgeraccount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='finance.RevenueCategory'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_revenuecorrectivejournalentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='correction_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrected_by_cje', to='finance.RevenueTransaction'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_revenuecorrectivejournalentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuecorrectivejournalentry', to='finance.RevenueLedgerAccount'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='restated_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restatement_for_cje', to='finance.RevenueTransaction'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='reversed_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_for_cje', to='finance.RevenueTransaction'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuecorrectivejournalentry', to='schoolauth.School'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuecorrectivejournalentry', to='finance.StudentAccount'),
        ),
        migrations.AddField(
            model_name='revenuecorrectivejournalentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_revenuecorrectivejournalentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenuecategory',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuecategory', to='finance.Fund'),
        ),
        migrations.AddField(
            model_name='revenuebudgetitem',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='finance.RevenueLedgerAccount'),
        ),
        migrations.AddField(
            model_name='revenuebudgetitem',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_revenuebudgetitem', to='finance.BudgetPeriod'),
        ),
        migrations.AddField(
            model_name='payeeaccount',
            name='payee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Payee'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_expensetransaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_expensetransaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensetransaction', to='finance.ExpenseLedgerAccount'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensetransaction', to='finance.PayeeAccount'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensetransaction', to='schoolauth.School'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_expensetransaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseledgeraccount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='finance.ExpenseCategory'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_expensecorrectivejournalentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='correction_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrected_by_cje', to='finance.ExpenseTransaction'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_expensecorrectivejournalentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensecorrectivejournalentry', to='finance.ExpenseLedgerAccount'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensecorrectivejournalentry', to='finance.PayeeAccount'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='restated_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restatement_for_cje', to='finance.ExpenseTransaction'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='reversed_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_for_cje', to='finance.ExpenseTransaction'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensecorrectivejournalentry', to='schoolauth.School'),
        ),
        migrations.AddField(
            model_name='expensecorrectivejournalentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_expensecorrectivejournalentry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories', to='personnel.Department'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensecategory', to='finance.Fund'),
        ),
        migrations.AddField(
            model_name='expensebudgetitem',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='finance.ExpenseLedgerAccount'),
        ),
        migrations.AddField(
            model_name='expensebudgetitem',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_expensebudgetitem', to='finance.BudgetPeriod'),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_periods', to='schoolauth.School'),
        ),
        migrations.AlterUniqueTogether(
            name='revenuebudgetitem',
            unique_together={('period', 'ledger_account')},
        ),
        migrations.AlterUniqueTogether(
            name='expensebudgetitem',
            unique_together={('period', 'ledger_account')},
        ),
    ]
