# Generated by Django 2.1.2 on 2018-10-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180920_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payeeaccount',
            name='payee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='personnel.Payee'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='students.Student'),
        ),
    ]
