# Generated by Django 2.1 on 2018-09-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180912_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['start', 'end']},
        ),
    ]
