# Generated by Django 2.0.7 on 2018-08-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180726_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensebudgetitem',
            old_name='ledgerAccount',
            new_name='ledger_account',
        ),
        migrations.RenameField(
            model_name='expensetransaction',
            old_name='ledgerAccount',
            new_name='ledger_account',
        ),
        migrations.RenameField(
            model_name='revenuebudgetitem',
            old_name='ledgerAccount',
            new_name='ledger_account',
        ),
        migrations.RenameField(
            model_name='revenuetransaction',
            old_name='ledgerAccount',
            new_name='ledger_account',
        ),
        migrations.RemoveField(
            model_name='employeeaccount',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeeaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeeaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employeeaccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='expensebudgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expensebudgetitem',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='expenseledgeraccount',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='amount_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='date_approved',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='date_issued',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='date_paid',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='discount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.EmployeeAccount'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='notes',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='partial_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.SupplierAccount'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='unit_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='revenuebudgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='revenuebudgetitem',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='revenuecategory',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='revenueledgeraccount',
            name='description',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='amount_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='date_issued',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='date_paid',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='notes',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='partial_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='expensebudgetitem',
            unique_together={('term', 'ledger_account')},
        ),
        migrations.AlterUniqueTogether(
            name='revenuebudgetitem',
            unique_together={('term', 'ledger_account')},
        ),
    ]
