# Generated by Django 2.0.7 on 2018-08-09 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20180808_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee'),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Supplier'),
        ),
    ]
