# Generated by Django 2.1.2 on 2018-11-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20181116_0750'),
        ('finance', '0003_auto_20181023_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('graduating_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_schoolfee', to='schools.GraduatingClass')),
            ],
        ),
        migrations.AddField(
            model_name='revenueledgeraccount',
            name='has_school_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_finance_schoolfee', to='finance.RevenueLedgerAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolfee',
            unique_together={('ledger_account', 'graduating_class')},
        ),
    ]
