# Generated by Django 2.1.2 on 2018-11-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20181116_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenueledgeraccount',
            old_name='has_school_fee',
            new_name='is_student_fee',
        ),
    ]
