# Generated by Django 2.1 on 2018-08-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180816_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetransaction',
            name='revised_by_cje',
        ),
        migrations.RemoveField(
            model_name='revenuetransaction',
            name='revised_by_cje',
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='corrected_by_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_to', to='finance.ExpenseCorrectiveJournalEntry'),
        ),
        migrations.AddField(
            model_name='revenuetransaction',
            name='corrected_by_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_to', to='finance.RevenueCorrectiveJournalEntry'),
        ),
    ]
