# Generated by Django 2.0.7 on 2018-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180808_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
