# Generated by Django 2.1.2 on 2019-01-03 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_auto_20181116_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetperiod',
            options={'ordering': ['start', 'end'], 'permissions': (('approve_budget', 'Can approve budgets'),), 'verbose_name': 'budget'},
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='approval_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Pending Approval'), ('A', 'Approved')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_budgetperiod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='date_submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_finance_budgetperiod', to=settings.AUTH_USER_MODEL),
        ),
    ]
