# Generated by Django 2.0.7 on 2018-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_term_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebudgetitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='expenseledgeraccount',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='revenuebudgetitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='revenuecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='revenueledgeraccount',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
