# Generated by Django 2.1 on 2018-08-17 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20180817_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='corrected_by_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_to', to='finance.ExpenseCorrectiveJournalEntry'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='restatement_for_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restated_in', to='finance.ExpenseCorrectiveJournalEntry'),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='reversal_for_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_in', to='finance.ExpenseCorrectiveJournalEntry'),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='corrected_by_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_to', to='finance.RevenueCorrectiveJournalEntry'),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='restatement_for_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restated_in', to='finance.RevenueCorrectiveJournalEntry'),
        ),
        migrations.AlterField(
            model_name='revenuetransaction',
            name='reversal_for_cje',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_in', to='finance.RevenueCorrectiveJournalEntry'),
        ),
    ]
