# Generated by Django 2.0.7 on 2018-08-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180809_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebudgetitem',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='expensebudgetitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expensebudgetitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='revenuebudgetitem',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='revenuebudgetitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='revenuebudgetitem',
            name='name',
        ),
    ]
