# Generated by Django 2.2 on 2019-04-12 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to='schoolauth.School')),
            ],
        ),
        migrations.CreateModel(
            name='GraduatingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduating_year', models.SmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('graduated', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduating_classes', to='schoolauth.School')),
            ],
            options={
                'unique_together': {('school', 'graduating_year')},
            },
        ),
    ]
