# Generated by Django 2.1 on 2018-09-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('school_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('canteen_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
