# Generated by Django 2.2 on 2019-04-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatingclass',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='class name'),
        ),
    ]
