# Generated by Django 2.1 on 2018-10-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolauth', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatingclass',
            name='graduating_year',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='graduatingclass',
            unique_together={('school', 'graduating_year')},
        ),
    ]
