# Generated by Django 2.1.2 on 2018-10-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20181016_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_graduating_years', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
