# Generated by Django 2.1.2 on 2018-11-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduatingclass',
            name='admission_fee',
        ),
        migrations.RemoveField(
            model_name='graduatingclass',
            name='canteen_fee',
        ),
        migrations.RemoveField(
            model_name='graduatingclass',
            name='school_fee',
        ),
    ]
